//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.InstallingLog = new HashSet<ReplacingLog>();
            this.RemovingLog = new HashSet<ReplacingLog>();
            this.EquipmentEvent = new HashSet<EquipmentEvent>();
            this.ServiceLog = new HashSet<ServiceLog>();
        }
    
        public System.Guid Id { get; set; }
        public string number { get; set; }
        public System.DateTime repairDate { get; set; }
        public System.DateTime serviceDate { get; set; }
        public Nullable<System.DateTime> nextVerificationDate { get; set; }
        public Nullable<System.DateTime> termDate { get; set; }
        public bool isWorking { get; set; }
        public bool isFree { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual MVPS MVPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplacingLog> InstallingLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplacingLog> RemovingLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentEvent> EquipmentEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceLog> ServiceLog { get; set; }
    }
}
