//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public System.Guid id { get; set; }
        public string number { get; set; }
        public System.DateTime repairDate { get; set; }
        public System.DateTime serviceDate { get; set; }
        public Nullable<System.DateTime> nextVerificationDate { get; set; }
        public Nullable<System.DateTime> termDate { get; set; }
        public bool isWorking { get; set; }
        public bool isFree { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual MVPS MVPS { get; set; }
    }
}
