//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public System.Guid id { get; set; }
        public Nullable<int> manufacturer { get; set; }
        public Nullable<int> type { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> repairDate { get; set; }
        public Nullable<System.DateTime> serviceDate { get; set; }
        public Nullable<System.DateTime> nextVerificationDate { get; set; }
        public Nullable<bool> isWorking { get; set; }
    
        public virtual EquipmentTypes EquipmentType { get; set; }
        public virtual Manufacturers Manufacturer { get; set; }
    }
}
