//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kipEntities : DbContext
    {
        public kipEntities()
            : base("name=kipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> EquipmentSet { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypeSet { get; set; }
        public virtual DbSet<Manufacturer> ManufacturerSet { get; set; }
        public virtual DbSet<SystemType> SystemTypeSet { get; set; }
        public virtual DbSet<MVPSRole> MVPSRoleSet { get; set; }
        public virtual DbSet<MVPSType> MVPSTypeSet { get; set; }
        public virtual DbSet<MVPS> MVPSSet { get; set; }
        public virtual DbSet<EquipmentRule> EquipmentRuleSet { get; set; }
        public virtual DbSet<ReplacingLog> ReplacingLogSet { get; set; }
        public virtual DbSet<Worker> WorkerSet { get; set; }
        public virtual DbSet<Position> PositionSet { get; set; }
        public virtual DbSet<EquipmentEvent> EquipmentEventSet { get; set; }
        public virtual DbSet<ServiceLog> ServiceLogSet { get; set; }
        public virtual DbSet<Shedule> SheduleSet { get; set; }
    }
}
